### ISSUE TITLE
root用户名更改后无法安装安全巡检

### ISSUE THREAD

**Issue by Rogers0007** [GuanceCloud/datakit#10]
linux服务器因等保要求，将root用户名改了，导致安全巡检无法安装。

![1](https://user-images.githubusercontent.com/90943783/196084273-7312dc09-7cce-44e2-b99a-8490cd0657a9.png)

**Comment by coanor** [comment]
可以尝试用 datakit 这个用户名安装一下。参见 `DK_USER_NAME ` 用法：https://docs.guance.com/datakit/datakit-install/#common-envs
