### ISSUE TITLE
dkebpf.Asset()函数找不到

### ISSUE THREAD

**Issue by Erica177** [GuanceCloud/datakit#12]
![image](https://user-images.githubusercontent.com/30773688/219593770-cf46e82f-e8ac-4b70-9a3a-7c7246e9433d.png)
![image](https://user-images.githubusercontent.com/30773688/219593819-092b7e8b-f685-45de-96b8-1e23cb193563.png)
请问这个dkebpf.Asset()函数在哪里呀，在c目录里面并没有找到对应的方法

**Comment by Ykaiyuan** [comment]
Asset是go-bindata编译后go文件中的函数，成功执行makefile文件后会产生

**Comment by vircoys** [comment]
后续版本将 go-bindata 替换成了 go:embed
