### ISSUE TITLE
prometheus数据接入失败

### ISSUE THREAD

**Issue by Haley-go** [GuanceCloud/datakit#20]
Hello，按照这个文档想接入更多的prometheus数据 https://docs.guance.com/integrations/prom/#prometheus-exporter
配置了两个外部地址
![image](https://github.com/GuanceCloud/datakit/assets/37686410/e71e2920-7f8b-454a-860a-cda44b40e3a5)
monitor上也看到了响应的input
![image](https://github.com/GuanceCloud/datakit/assets/37686410/505d5a0c-f5d6-4660-a513-5db461289768)

但是观测云指标集里一直看不到数据上来

用了 `datakit debug --prom-conf prom.conf` 能看到有input，datakit容器没有任何的错误日志，`datakit_filter_point_dropped_total `似乎默认也没有被采集无法查询到
![image](https://github.com/GuanceCloud/datakit/assets/37686410/6e171760-7101-48b2-be86-0fbcaadd5cd8)
![image](https://github.com/GuanceCloud/datakit/assets/37686410/e67efc86-5b49-47d8-a85e-d6ed526847e6)

为了防止1000个指标过多，relabel到17个之后还是不行
![image](https://github.com/GuanceCloud/datakit/assets/37686410/e2a43050-07e4-4257-bf78-20dc70cc5538)

请问还有别的排障手段吗，datakit跟gateway的网络没问题，其他指标一直都正常写入

**Comment by Haleygo** [comment]
![image](https://github.com/GuanceCloud/datakit/assets/39937150/b01565d6-2842-4b2e-907d-bb1ba4328edb)
容器日志级别调整到debug，还是看不到更多信息

**Comment by Haley-go** [comment]
容器日志级别调整到debug，还是看不到更多信息
![image](https://github.com/GuanceCloud/datakit/assets/37686410/c5d3d8cc-d981-4c87-8446-847ad5f77854)

**Comment by coanor** [comment]
> 容器日志级别调整到debug，还是看不到更多信息 ![image](https://private-user-images.githubusercontent.com/37686410/255612140-c5d3d8cc-d981-4c87-8446-847ad5f77854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODUwNzYsIm5iZiI6MTcwNTM4NDc3NiwicGF0aCI6Ii8zNzY4NjQxMC8yNTU2MTIxNDAtYzVkM2Q4Y2MtZDk4MS00Yzg3LTg0NDYtODQ3YWQ1Zjc3ODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZGMyZmQxMWI2Zjg1OWY3ZGNlOGU0Zjc4NjkyOGI5NmMzOWIzZjQ3YTcxMDk2YmU1Yzk3YWVhMTJiODZmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kfvxs8_DD84itjLZ-oNxCZ3B_7zYxt6ALtadhnBsQ_M)

默认情况下，日志是输出到容器内部的 */var/log/datakit/log* 中。

**Comment by coanor** [comment]
> datakit debug --prom-conf prom.conf

从截图看，采集器已经可以采集到数据了，可以用 `datakit monitor -V` 看下，它会展示更多的可观测数据以定位具体问题。
