### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by CyshallChan** [GuanceCloud/datakit#4]
按照README中的操作无法编译，错误如下：
<img width="1228" alt="CleanShot 2022-07-22 at 13 13 11@2x" src="https://user-images.githubusercontent.com/22564041/180367484-29ec132a-3fe0-4a23-a669-bdd2496526dd.png">

**Comment by vircoys** [comment]
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2 \
  && go install github.com/gobuffalo/packr/v2/packr2@latest \
  && go install mvdan.cc/gofumpt@latest \
  && go install golang.org/x/tools/cmd/goyacc@latest \
  && go install -a -v github.com/go-bindata/go-bindata/...@latest \
  && cp -r $HOME/go/bin/* /usr/local/bin

**Comment by vircoys** [comment]
> I meet this same problem，anybody solve it ？

Please try removing files that are not under version control
```shell
git clean -xdn

git clean -xdf
```

**Comment by Albertchamberlain** [comment]
如果遇到如下错误
![image](https://github.com/GuanceCloud/datakit/assets/47343901/6530d3cb-4f50-4a8c-be8b-9ca342bf1f49)

可以改为如下，即可在容器内编译成功

PWD=/home/Your_Account_Name/datakit

sudo docker run -ti -v $PWD:/root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit -w /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit vircoys/datakit-developer:1.6 /bin/bash

**Comment by Albertchamberlain** [comment]
> 

Ubuntu 22.04 LTS
