### ISSUE TITLE
host_processes.conf文件中的白名单配置未生效

### ISSUE THREAD

**Issue by Rogers0007** [GuanceCloud/datakit#9]
在host_processes.conf文件中添加了进程白名单，但是没生效，还是会把所有进程数据都采集上来。（Linux服务器试过也是有这个问题）

![微信截图_20221013202547](https://user-images.githubusercontent.com/90943783/195770554-346ddbf6-dfdf-4485-80b9-42ea9a591122.png)
![10](https://user-images.githubusercontent.com/90943783/195770553-3aadba5a-b6b6-4cd8-886b-4498e35584df.png)

**Comment by coanor** [comment]
进程对象采集是不受白名单控制的，第二张截图中看到的都是进程对象。建议去进程指标中看一下，是否只有白名单中的进程采集上来了。
